import { RunoError } from "../errors";
import { log } from "../log";
import type { ExposeContext, ExposeProvider, ExposeService } from "./types";

/**
 * Automatic HTTPS on the VM's own IP — the zero-account default.
 *
 * Caddy terminates TLS and reverse-proxies to each service; the hostname comes
 * from sslip.io, which resolves any name carrying an embedded IP
 * (`56-125-87-78.sslip.io` → 56.125.87.78), so a real Let's Encrypt
 * certificate can be issued for it. No account, no token, no DNS zone: clone
 * runo and the first `runo up` already hands out an https:// link that opens
 * in anyone's browser, WebSockets included.
 *
 * The trade-off vs a named tunnel: the hostname carries the IP, and the IP
 * changes on every suspend/resume — fine for a dev box, not for a link pasted
 * into a pull request (that is what expose.domain is for).
 */

const CADDYFILE = "/etc/caddy/Caddyfile";

/** sslip.io hostname for this env: <service>.<ip-dashed>.sslip.io. */
function hostFor(svc: ExposeService, ip: string): string {
  const base = `${ip.replaceAll(".", "-")}.sslip.io`;
  return svc.primary ? base : `${svc.name.replace(/[^a-zA-Z0-9-]/g, "-")}.${base}`;
}

function installScript(): string {
  return [
    "if ! command -v caddy >/dev/null 2>&1; then",
    "  sudo apt-get install -y -qq debian-keyring debian-archive-keyring apt-transport-https curl >/dev/null",
    "  curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | sudo gpg --batch --yes --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg",
    "  curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' | sudo tee /etc/apt/sources.list.d/caddy-stable.list >/dev/null",
    "  sudo apt-get update -qq >/dev/null",
    "  sudo apt-get install -y -qq caddy >/dev/null",
    "fi",
    "command -v caddy >/dev/null 2>&1 || { echo 'caddy install failed' >&2; exit 1; }",
  ].join("\n");
}

function caddyfile(services: ExposeService[], ip: string): string {
  const blocks = services.map((s) =>
    [
      `${hostFor(s, ip)} {`,
      `\treverse_proxy 127.0.0.1:${s.port} {`,
      // dev servers are slow to answer the first compile of a route; do not
      // give up on them before the browser would
      "\t\ttransport http {",
      "\t\t\tread_timeout 300s",
      "\t\t}",
      "\t}",
      "}",
    ].join("\n"),
  );
  return `# Generated by runo (expose.mode: https) — edits are overwritten on the next up.\n${blocks.join("\n\n")}\n`;
}

export const httpsExpose: ExposeProvider = {
  name: "https",

  async up(ctx: ExposeContext): Promise<Record<string, string>> {
    if (ctx.services.length === 0) return {};
    if (!ctx.rt.ip)
      throw new RunoError("The VM has no public IP yet", "Run `runo resume` and try again");
    const ip = ctx.rt.ip;

    // Only 80/443 face the world — the services themselves stay closed, which
    // is strictly better than the ip mode this replaces.
    await ctx.provider.ensurePorts([80, 443]);

    log.step(
      `publishing ${ctx.services.map((s) => `${s.name}:${s.port}`).join(", ")} over HTTPS (Caddy + sslip.io)…`,
    );
    const conf = caddyfile(ctx.services, ip);
    const script = [
      installScript(),
      `sudo mkdir -p $(dirname ${CADDYFILE})`,
      `sudo tee ${CADDYFILE} >/dev/null <<'CADDYFILE_EOF'`,
      conf,
      "CADDYFILE_EOF",
      "sudo systemctl enable caddy >/dev/null 2>&1 || true",
      // reload keeps issued certificates and open connections; restart is the
      // fallback when the daemon is not running yet
      "sudo systemctl reload caddy 2>/dev/null || sudo systemctl restart caddy",
      "sudo systemctl is-active --quiet caddy || { echo 'caddy did not start' >&2; sudo journalctl -u caddy -n 20 --no-pager >&2; exit 1; }",
    ].join("\n");

    const r = await ctx.provider.exec(ctx.rt, script, { timeoutMs: 5 * 60_000 });
    if (r.exitCode !== 0)
      throw new RunoError(
        "Could not configure automatic HTTPS on the VM",
        r.stderr.trim().split("\n").slice(-8).join("\n"),
      );

    const urls: Record<string, string> = {};
    for (const s of ctx.services) urls[s.name] = `https://${hostFor(s, ip)}`;
    return urls;
  },

  async down(): Promise<void> {
    // Nothing lives off the VM: the certificate dies with the instance and the
    // hostname belongs to the IP, not to us.
  },
};
