import {readFile,writeFile,mkdir,rm,cp} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
import {marked} from 'marked';
const base=path.dirname(fileURLToPath(import.meta.url));
const out=path.join(base,'dist');
const origin='https://runo.sh';
const repo='https://github.com/kodustech/runo';
const escape=s=>s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const nav=`<a class="skip" href="#main">Skip to content</a><header class="header wrap"><a class="brand" href="/" aria-label="Runo home"><img src="/assets/mark.svg" width="28" height="28" alt="">runo</a><nav aria-label="Main navigation"><a href="/docs/quickstart/">Docs</a><a href="${repo}">GitHub <span aria-hidden="true">↗</span></a></nav></header>`;
const footer=`<footer class="wrap footer"><a class="brand" href="/">runo</a><div><a href="${repo}">Source code</a><a href="https://kodus.io">By Kodus</a><a href="/docs/quickstart/">Documentation</a></div></footer>`;
const schema={'@context':'https://schema.org','@type':'SoftwareApplication',name:'Runo',url:origin,description:'Remote development environments per Git branch on AWS for developers using Claude Code or Codex.',applicationCategory:'DeveloperApplication',operatingSystem:'macOS, Linux',author:{'@type':'Organization',name:'Kodus',url:'https://kodus.io'},sameAs:repo};
function shell(title,description,route,body,kind='home') {return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escape(title)}</title><meta name="description" content="${escape(description)}"><link rel="canonical" href="${origin}${route}"><meta property="og:type" content="website"><meta property="og:site_name" content="Runo"><meta property="og:title" content="${escape(title)}"><meta property="og:description" content="${escape(description)}"><meta property="og:url" content="${origin}${route}"><meta name="twitter:card" content="summary"><meta name="theme-color" content="#111713"><link rel="icon" href="/assets/mark.svg" type="image/svg+xml"><link rel="stylesheet" href="/assets/fonts.css"><link rel="stylesheet" href="/assets/style.css">${kind==='home'?`<script type="application/ld+json">${JSON.stringify(schema)}</script>`:''}<script src="/assets/site.js" defer></script></head><body class="${kind}">${nav}${body}${footer}</body></html>`;}
async function page(route,title,description,body,kind){const dir=path.join(out,route);await mkdir(dir,{recursive:true});await writeFile(path.join(dir,'index.html'),shell(title,description,route,body,kind));}
await rm(out,{recursive:true,force:true});await mkdir(out,{recursive:true});await cp(path.join(base,'assets'),path.join(out,'assets'),{recursive:true});
const home=`<main id="main">
<section class="hero wrap"><p class="eyebrow"><span class="branch-icon" aria-hidden="true">⑂</span> Remote development environments</p><div class="hero-layout"><h1><span class="hero-line">A running app.</span><span class="hero-line">For every <span class="accent">branch.</span></span></h1><div class="branch-map" role="img" aria-label="A repository branches into checkout-fix and search-fix. Each has a separate AWS environment running its own application on port 3000."><div class="map-source"><span class="repo-symbol" aria-hidden="true">⑂</span><code>your-repository</code><span class="map-label">main</span></div><div class="map-environments"><svg class="map-rails" viewBox="0 0 65 205" preserveAspectRatio="none" aria-hidden="true"><path class="rail-base" d="M13 0 V159 Q13 168 23 168 H64 M13 44 H64"/><path class="rail-active" pathLength="1" d="M13 0 V159 Q13 168 23 168 H64 M13 44 H64"/><circle class="rail-dot" cx="13" cy="44" r="4"/></svg><div class="map-env env-one"><div><code>task/checkout-fix</code><span class="env-cloud">AWS</span></div><div class="env-runtime"><span class="env-dot" aria-hidden="true"></span><span>app :3000</span><span>database</span></div></div><div class="map-env env-two"><div><code>task/search-fix</code><span class="env-cloud">AWS</span></div><div class="env-runtime"><span class="env-dot" aria-hidden="true"></span><span>app :3000</span><span>database</span></div></div></div><p class="map-caption">Same ports. Separate machines.</p></div></div><button class="replay-motion" type="button" aria-label="Replay the branch diagram animation">↻ Replay diagram</button><div class="hero-bottom"><p>Give each Git branch its own AWS environment.<br class="desktop"> Run your app alongside Claude Code or Codex, then share a preview and test the change.</p><a class="button" href="#walkthrough">See how it works <span class="play-small" aria-hidden="true">▶</span></a></div><div class="hero-meta"><span>YOUR AWS ACCOUNT</span><span>YOUR REPOSITORY</span><span>CLAUDE CODE + CODEX</span><a href="${repo}">Explore the source ↗</a></div></section>
<section class="watch wrap" id="walkthrough" aria-labelledby="diagram-title"><div class="section-label"><h2 id="diagram-title">Follow a change through Runo.</h2><span>AN INTERACTIVE DIAGRAM</span></div><div class="workflow-diagram" data-phase="0"><div class="diagram-toolbar"><div><span class="diagram-brand">⑂</span><span>ONE BRANCH / ONE ENVIRONMENT</span></div><button class="diagram-play" type="button" aria-label="Play the workflow animation">▶ Play flow</button></div><div class="diagram-stage"><div class="diagram-local"><span class="diagram-kicker">YOUR MACHINE</span><div class="diagram-node repo-node"><span class="node-icon" aria-hidden="true">⑂</span><h3>Your repository</h3><code>task/checkout-fix</code></div><div class="local-evidence"><span class="node-icon" aria-hidden="true">✓</span><div><h3>Validation results</h3><p>Logs + JSON + Markdown</p></div></div></div><div class="diagram-connection"><span class="connection-label">code + recipe</span><div class="connection-track outbound"><i></i></div><span class="connection-label lower-label">changes + evidence</span><div class="connection-track inbound"><i></i></div></div><div class="diagram-cloud"><div class="cloud-heading"><span class="diagram-kicker">DEDICATED AWS VM</span><span class="cloud-id">checkout-fix</span></div><div class="cloud-contents"><div class="agent-node"><span class="agent-icon" aria-hidden="true">✳</span><h3>Your coding agent</h3><p>Claude Code / Codex</p></div><div class="service-pair"><div><span class="service-mark" aria-hidden="true">&gt;_</span><h3>Application</h3><code>:3000</code></div><div><span class="service-mark" aria-hidden="true">▤</span><h3>Database</h3><code>from your recipe</code></div></div></div><div class="preview-node"><span aria-hidden="true">◎</span><span>Open the application</span><span class="preview-caption">preview URL</span></div></div></div><div class="diagram-bottom"><code class="diagram-command">$ runo new checkout-fix</code><span>ILLUSTRATED WORKFLOW</span></div></div><div class="diagram-controls" role="group" aria-label="Explore the workflow"><button type="button" data-step="0" aria-pressed="true"><span>01</span> Create</button><button type="button" data-step="1" aria-pressed="false"><span>02</span> Work</button><button type="button" data-step="2" aria-pressed="false"><span>03</span> Preview</button><button type="button" data-step="3" aria-pressed="false"><span>04</span> Validate</button></div><p class="diagram-explanation" aria-live="polite">Your recipe defines the application and services. Runo provisions the branch's environment on AWS.</p><p class="diagram-footnote">Select a step to explore. Commands after creation run from the printed worktree path. Database setup and validation depend on your recipe.</p></section>
<section class="why wrap" aria-labelledby="why-title"><div><p class="eyebrow">The part after the checkout</p><h2 id="why-title">Your branch needs<br>a place to run.</h2></div><div class="why-copy"><p>Separate checkouts still share your machine. Start another app and you can run into the same ports, the same database, and a laptop doing too much.</p><p>Runo puts each environment on a dedicated VM. Your recipe defines the services and data it needs. The agent works there, and you can open the app before a PR exists.</p><a class="text-link" href="/docs/branch-environments/">Read about branch environments <span aria-hidden="true">↗</span></a></div></section>
<section class="learn wrap" aria-labelledby="learn-title"><div class="section-label"><h2 id="learn-title">Get to know Runo.</h2><span>NOTES & DOCUMENTATION</span></div><div class="reading-list"><a href="/docs/quickstart/"><span class="read-kind">START HERE</span><h3>Your first remote environment</h3><p>Run the example API with Postgres. Open it, validate it, and clean up.</p><span aria-hidden="true">↗</span></a><a href="/docs/agents/"><span class="read-kind">CODING AGENTS</span><h3>Claude Code and Codex on AWS</h3><p>Set up credentials and work inside a remote environment.</p><span aria-hidden="true">↗</span></a><a href="/docs/branch-environments/"><span class="read-kind">PARALLEL DEVELOPMENT</span><h3>Separate branches, separate services</h3><p>How worktrees, ports and databases fit together.</p><span aria-hidden="true">↗</span></a></div></section>
<section class="questions wrap" aria-labelledby="questions-title"><div><p class="eyebrow">Before you start</p><h2 id="questions-title">A few useful details.</h2></div><div class="faq"><details><summary>Where does Runo run?</summary><p>The current runtime provider is AWS EC2. Use your AWS credentials directly, or connect to a team control plane whose operator manages AWS access.</p></details><details><summary>Does each branch get its own database?</summary><p>It does when your recipe provisions a database in that environment. If you point two environments at the same external database, they still share that data. Migrations and seeding are configured in the recipe.</p></details><details><summary>Does Runo replace Claude Code or Codex?</summary><p>Runo runs the agent you choose in the remote environment. You provide its credentials, and the agent works alongside the application and configured services.</p></details><details><summary>What does it cost to run?</summary><p>AWS infrastructure and agent usage can incur charges. Suspending a VM preserves its disk, so storage can still cost money. Destroy environments you no longer need after saving your changes.</p></details><details><summary>Are previews private?</summary><p>The preview URL does not add authentication to your application. Use development credentials and data, and configure application access control where needed.</p></details></div></section>
<section class="closing wrap"><div><h2>Take a closer look.</h2><p>Start with the example app, or read the code.</p></div><div class="closing-links"><a class="button" href="/docs/quickstart/">Read the quickstart</a><a class="text-link" href="${repo}">Explore GitHub ↗</a></div></section>
</main>`;
await page('/','Runo | Remote environments for coding agents','Run your app and coding agent in a separate AWS environment for each Git branch. Learn how Runo handles previews and validation with Claude Code or Codex.',home,'home');
const docs=[['quickstart','Create your first remote development environment','Try Runo with an example API and Postgres on AWS. Install the CLI, start a branch environment, run validation and clean up.'],['agents','Run Claude Code or Codex on AWS with Runo','Configure agent credentials, start a remote coding session and validate your application in its branch environment.'],['branch-environments','Separate application environments for Git branches','Understand worktree port conflicts, separate database services and when a remote environment per branch can help.'],['reference','CLI and environment reference','Configure Runo services, profiles, validation and runtime lifecycle.'],['workflow','How Runo environments work','Follow a Git branch through a remote AWS environment, coding-agent session, application preview and validation.']];
const docPaths=new Set(docs.map(([slug])=>slug));
for(const [slug,title,desc] of docs){let md=await readFile(path.join(base,'../docs',slug+'.md'),'utf8');md=md.replace(/\]\(([^)]+\.md)(#[^)]*)?\)/g,(_,target,hash='')=>{const name=path.basename(target,'.md');return `](${docPaths.has(name)?'/docs/'+name+'/':repo+'/blob/main/docs/'+target}${hash})`;});const html=marked.parse(md);const side=docs.map(([s,t])=>`<a ${s===slug?'aria-current="page"':''} href="/docs/${s}/">${s==='quickstart'?'Quickstart':s==='agents'?'Coding agents':s==='workflow'?'How it works':s==='reference'?'Command reference':'Branch environments'}</a>`).join('');await page(`/docs/${slug}/`,`${title} | Runo`,desc,`<main id="main" class="docs-layout wrap"><aside aria-label="Documentation navigation"><p class="eyebrow">DOCUMENTATION</p>${side}</aside><article class="prose">${html}<div class="doc-end"><a href="${repo}/blob/main/docs/${slug}.md">View this page on GitHub</a><span>Runo documentation</span></div></article></main>`,'docs');}
await writeFile(path.join(out,'robots.txt'),`User-agent: *\nAllow: /\n\nUser-agent: OAI-SearchBot\nAllow: /\n\nSitemap: ${origin}/sitemap.xml\n`);
await writeFile(path.join(out,'sitemap.xml'),`<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${['/',...docs.map(([s])=>`/docs/${s}/`)].map(p=>`<url><loc>${origin}${p}</loc></url>`).join('')}</urlset>`);
await writeFile(path.join(out,'404.html'),shell('Page not found | Runo','This page does not exist.','/404',`<main id="main" class="wrap missing"><p class="eyebrow">404</p><h1>This branch goes nowhere.</h1><a class="button" href="/">Back to Runo</a></main>`,'error').replace('<meta name="description"','<meta name="robots" content="noindex"><meta name="description"'));
console.log(`Built ${docs.length+1} pages in website/dist`);
