import { existsSync, readFileSync } from "node:fs";
import { AGENT_ENV_PATH } from "./config";
import { RunoError } from "./errors";

const KNOWN_KEYS = ["ANTHROPIC_API_KEY", "OPENAI_API_KEY", "CLAUDE_CODE_OAUTH_TOKEN"] as const;

/**
 * Resolves agent credentials:
 *  1. process env vars;
 *  2. ~/.kodus/agent.env (global, independent of RUNO_HOME; KEY=value format).
 * NEVER log/print the returned values.
 */
export function resolveAgentEnv(): Record<string, string> {
  const fromFile: Record<string, string> = {};
  if (existsSync(AGENT_ENV_PATH)) {
    for (const line of readFileSync(AGENT_ENV_PATH, "utf8").split("\n")) {
      const t = line.trim();
      if (!t || t.startsWith("#")) continue;
      const eq = t.indexOf("=");
      if (eq <= 0) continue;
      const key = t.slice(0, eq).trim();
      let val = t.slice(eq + 1).trim();
      if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'")))
        val = val.slice(1, -1);
      fromFile[key] = val;
    }
  }
  const out: Record<string, string> = {};
  for (const key of KNOWN_KEYS) {
    const v = process.env[key] ?? fromFile[key];
    if (v) out[key] = v;
  }
  return out;
}

export function requireAgentEnv(agent: "claude" | "codex"): Record<string, string> {
  const env = resolveAgentEnv();
  if (agent === "claude") {
    // Subscription first: headless token generated by `claude setup-token`.
    // When present it travels ALONE (an invalid ANTHROPIC_API_KEY in the same
    // environment would break the CLI's auth).
    if (env.CLAUDE_CODE_OAUTH_TOKEN)
      return { CLAUDE_CODE_OAUTH_TOKEN: env.CLAUDE_CODE_OAUTH_TOKEN };
    if (env.ANTHROPIC_API_KEY) return { ANTHROPIC_API_KEY: env.ANTHROPIC_API_KEY };
    throw new RunoError(
      `No credentials found for the "claude" agent`,
      `Two options, via env vars or ${AGENT_ENV_PATH} (chmod 600): (1) subscription — run \`claude setup-token\` on your laptop and save the line CLAUDE_CODE_OAUTH_TOKEN=<token>; (2) API key — ANTHROPIC_API_KEY=<value>. Your laptop's interactive OAuth login does not travel to the VM.`,
    );
  }
  if (!env.OPENAI_API_KEY) {
    throw new RunoError(
      `OPENAI_API_KEY not found for the "codex" agent`,
      `Export OPENAI_API_KEY in your environment OR add the line "OPENAI_API_KEY=<value>" to ${AGENT_ENV_PATH} (chmod 600). Alternative: run \`codex login\` interactively inside \`runo agent codex\`.`,
    );
  }
  return { OPENAI_API_KEY: env.OPENAI_API_KEY };
}
